#define principal main
#define imprimirf printf
#define escanearf scanf
#define enquanto while
#define para for
#define se if
#define se_nao else
#define carac char
#define vazio void
#define faca do
#define quebrar break
#define retornar return 
#define trocar switch
#define caso case 
#define padrao default 
#define livrar free 
#define alocarMemoria malloc
#define nada NULL 
#define tamanhode sizeof
#define dobro double